In [1]:
import numpy as np

In [2]:
u = np.array([2,3,4,5,6]) #vector

In [3]:
2 * u

array([ 4,  6,  8, 10, 12])

In [49]:
v = np.array([6,5,4,3,2])

In [50]:
v.shape

(5,)

In [51]:
u + v 

array([8, 8, 8, 8, 8])

In [52]:
u - v

array([-4, -2,  0,  2,  4])

In [53]:
u * v

array([12, 15, 16, 15, 12])

In [54]:
u @ v #dot product

np.int64(70)

In [55]:
u.dot(v)

np.int64(70)

In [56]:
def dotproduct(u , v):
    assert u.shape[0] == v.shape[0]
    res = 0 
    for i in range(len(u)):
        res = res + u[i] * v[i]
    return res

In [57]:
dotproduct(u , v)

np.int64(70)

In [12]:
U = np.array(
    [[2,3,4],
    [5,6,7],
    [8,9,1]]
)

In [13]:
U

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [25]:
U.shape

(3, 3)

In [58]:
x = np.array([3,4,5])

In [59]:
V = np.array(
    [[8,9 ,1 ],
    [5,6,7],
    [2,3,4]]
)

In [60]:
V

array([[8, 9, 1],
       [5, 6, 7],
       [2, 3, 4]])

In [63]:
def matrixvectormultiplication(U , v):
    assert U.shape[1] == v.shape[0]
    result = np.zeros(v.shape[0])
    for i in range(U.shape[0]):
        for j in range(U.shape[1]):
            result[i] += + U[i][j] * v[j]
    return result


In [64]:
matrixvectormultiplication(U , x)

array([38., 74., 65.])

In [65]:
U.dot(x)

array([38, 74, 65])